import config
from src.models.inletter_model import insert_inletter
from src.models.outletter_model import insert_outletter


def seed_inletters():
    sample_inletters = [
        (
            "2026-06-01",
            "2026-06-01",
            "Incoming Memo",
            "Request for Annual Budget Review",
            "Department-2",
            "Finance Department",
            "Normal",
            "High",
            "CF-2026-001",
            "/path/to/budget_request.pdf",
            "Please review the attached annual budget request.",
            "Department-1",
        ),
        (
            "2026-05-28",
            "2026-05-29",
            "Official Letter",
            "Invitation to Joint Planning Meeting",
            "Department-3",
            "Planning Committee",
            "Confidential",
            "Medium",
            "CF-2026-002",
            "",
            "Meeting scheduled for next Tuesday at 10am.",
            "Department-1",
        ),
        (
            "2026-06-02",
            "2026-06-02",
            "Notification",
            "New Staff Appointment Notice",
            "Department-4",
            "HR Department",
            "Normal",
            "Low",
            "CF-2026-003",
            "",
            "New employee appointment attached.",
            "Department-5",
        ),
        (
            "2026-06-04",
            "2026-06-04",
            "Incoming Memo",
            "Schedule Change for Staff Training",
            "Department-5",
            "Training Office",
            "Normal",
            "Medium",
            "CF-2026-004",
            "",
            "Please note the new training schedule in the attached memo.",
            "Department-2",
        ),
        (
            "2026-05-25",
            "2026-05-26",
            "Official Letter",
            "Audit Report Submission",
            "Department-1",
            "Audit Committee",
            "Confidential",
            "High",
            "CF-2026-005",
            "/path/to/audit_report.pdf",
            "Audit report attached for review.",
            "Department-3",
        ),
        (
            "2026-06-03",
            "2026-06-03",
            "Notification",
            "Equipment Maintenance Notice",
            "Department-7",
            "Maintenance Team",
            "Normal",
            "Low",
            "CF-2026-006",
            "",
            "Maintenance will happen on Friday evening.",
            "Department-1",
        ),
        (
            "2026-06-02",
            "2026-06-02",
            "Incoming Memo",
            "Policy Update for Data Security",
            "Department-8",
            "IT Security",
            "Confidential",
            "High",
            "CF-2026-007",
            "/path/to/security_policy.pdf",
            "Please circulate the updated data security policy.",
            "Department-4",
        ),
        (
            "2026-05-20",
            "2026-05-21",
            "Official Letter",
            "Request for Vendor Contract Approval",
            "Department-9",
            "Procurement Office",
            "Normal",
            "Medium",
            "CF-2026-008",
            "",
            "Contract approval requested for vendor services.",
            "Department-2",
        ),
        (
            "2026-06-05",
            "2026-06-05",
            "Notification",
            "Office Closure Notice",
            "Department-10",
            "Operations Team",
            "Normal",
            "High",
            "CF-2026-009",
            "",
            "Office will be closed due to public holiday.",
            "Department-1",
        ),
        (
            "2026-06-06",
            "2026-06-06",
            "Incoming Memo",
            "Invitation to Performance Review Meeting",
            "Department-6",
            "HR Department",
            "Normal",
            "Medium",
            "CF-2026-010",
            "",
            "Please join the review meeting next Wednesday.",
            "Department-3",
        ),
    ]

    print("Seeding inletter sample data...")
    for index, inletter in enumerate(sample_inletters, start=1):
        success = insert_inletter(inletter)
        print(f"  Inletter {index}: {'Inserted' if success else 'Failed'}")


def seed_outletters():
    sample_outletters = [
        (
            "2026-06-03",
            "Outgoing Memo",
            "Approval for Training Program",
            "Department-6",
            "Normal",
            "High",
            "CF-2026-101",
            "/path/to/training_approval.pdf",
            "Send approved training program details.",
            "Department-1",
        ),
        (
            "2026-05-30",
            "Official Notice",
            "Updated Procurement Guidelines",
            "Department-7",
            "Normal",
            "Medium",
            "CF-2026-102",
            "",
            "Please distribute the new procurement guidelines.",
            "Department-3",
        ),
        (
            "2026-06-01",
            "Circular",
            "Security Awareness Bulletin",
            "Department-8",
            "Low",
            "Low",
            "CF-2026-103",
            "",
            "Circular to all departments for security best practices.",
            "Department-2",
        ),
        (
            "2026-06-04",
            "Outgoing Letter",
            "Approval of Facility Renovation",
            "Department-9",
            "Normal",
            "Medium",
            "CF-2026-104",
            "/path/to/renovation_approval.pdf",
            "Facility renovation has been approved.",
            "Department-1",
        ),
        (
            "2026-06-02",
            "Official Notice",
            "Staff Meeting Summary",
            "Department-4",
            "Normal",
            "Low",
            "CF-2026-105",
            "",
            "Summary of the staff meeting held last Friday.",
            "Department-1",
        ),
        (
            "2026-05-31",
            "Memo",
            "Request for IT Support",
            "Department-3",
            "Confidential",
            "High",
            "CF-2026-106",
            "",
            "Please provide IT support for the new software rollout.",
            "Department-6",
        ),
        (
            "2026-06-05",
            "Circular",
            "Holiday Schedule Update",
            "Department-2",
            "Normal",
            "Low",
            "CF-2026-107",
            "",
            "Updated holiday schedule is now available.",
            "Department-5",
        ),
        (
            "2026-05-29",
            "Outgoing Memo",
            "Confirmation of Vendor Delivery",
            "Department-10",
            "Normal",
            "Medium",
            "CF-2026-108",
            "",
            "Vendor delivery confirmation has been issued.",
            "Department-3",
        ),
        (
            "2026-06-06",
            "Official Letter",
            "Invitation to External Review Board",
            "Department-1",
            "Confidential",
            "High",
            "CF-2026-109",
            "/path/to/review_invitation.pdf",
            "Invite the external review board members.",
            "Department-4",
        ),
        (
            "2026-06-07",
            "Notice",
            "Reminder for Quarterly Report Submission",
            "Department-5",
            "Normal",
            "High",
            "CF-2026-110",
            "",
            "Reminder to submit quarterly reports by end of week.",
            "Department-2",
        ),
    ]

    print("Seeding outletter sample data...")
    for index, outletter in enumerate(sample_outletters, start=1):
        success = insert_outletter(outletter)
        print(f"  Outletter {index}: {'Inserted' if success else 'Failed'}")


def main():
    print("Initializing database and tables...")
    config.init_db()
    seed_inletters()
    seed_outletters()
    print("Seed complete.")


if __name__ == "__main__":
    main()
